# Clase de análisis de datos

In [1]:
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
st.title("Hello, Streamlit!")

2025-05-14 17:06:11.542 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-14 17:06:11.707
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /home/rikamomoe/Escritorio/Programming/Jupyter Notebook/curso_python_protecsa/.venv/lib/python3.12/site-packages/ipykernel_launcher.py [ARGUMENTS]
2025-05-14 17:06:11.708 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

In [3]:
# Comando para ejecutar el script:
# streamlit run clase_analisis_datos.py

In [4]:
data = pd.read_csv("Computos2006-Presidente.txt", sep="|")
print("Número de entradas: ", data.shape)
data

Número de entradas:  (130788, 23)

,ID_ESTADO,DISTRITO,SECCION,ID_CASILLA,TIPO_CASILLA,EXT_CONTIGUA,TIPO_CANDIDATURA,TIPO_ACTA,LISTA_NOMINAL,NO_VOTOS_NULOS,...,ORDEN,PAN,APM,PBT,NA,ASDC,MUNICIPIO,PAQUETE_ENTREGADO,CASILLA_INSTALADA,FECHA_HORA
0,1,1,0,1,B,0,6,NaN,120,0.0,...,1,53.0,4.0,18.0,0.0,1.0,0,NaN,NaN,05/07/2006 23:22:10
1,1,1,338,1,B,0,1,1.0,689,12.0,...,1,202.0,45.0,65.0,12.0,12.0,2,1.0,1.0,05/07/2006 08:17:05
2,1,1,338,1,C,0,1,1.0,689,7.0,...,2,175.0,38.0,56.0,3.0,8.0,2,1.0,1.0,05/07/2006 08:22:24
3,1,1,339,1,B,0,1,1.0,630,0.0,...,3,165.0,50.0,48.0,7.0,13.0,2,1.0,1.0,05/07/2006 08:24:47
4,1,1,339,1,C,0,1,1.0,631,6.0,...,4,174.0,64.0,32.0,9.0,7.0,2,1.0,1.0,05/07/2006 08:25:03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130783,32,4,1706,1,B,0,1,1.0,67,1.0,...,513,2.0,32.0,21.0,0.0,0.0,54,1.0,1.0,05/07/2006 18:34:20
130784,32,4,1707,1,B,0,1,1.0,181,5.0,...,514,18.0,49.0,29.0,0.0,0.0,54,1.0,1.0,05/07/2006 18:34:44
130785,32,4,1708,1,B,0,1,1.0,273,1.0,...,515,6.0,75.0,82.0,0.0,2.0,54,1.0,1.0,05/07/2006 18:35:01
130786,32,4,1709,1,B,0,1,1.0,277,9.0,...,516,13.0,51.0,108.0,0.0,2.0,54,1.0,1.0,05/07/2006 18:35:17
130787,32,4,1710,1,B,0,1,1.0,485,9.0,...,517,23.0,63.0,85.0,2.0,2.0,54,1.0,1.0,05/07/2006 18:35:36

In [5]:
idstate = {1: 'Aguascalientes', 2:'Baja California', 3: 'Baja California Sur', 4: 'Campeche',
           5: 'Coahuila', 6: 'Colima', 7: 'Chiapas', 8: 'Chihuahua', 9:'CDMX', 10: 'Durango',
           11: 'Guanajuato', 12: 'Guerrero', 13: 'Hidalgo', 14: 'Jalisco', 15: 'México',
           16: 'Michoacán', 17: 'Morelos', 18: 'Nayarit', 19: 'Nuevo León', 20: 'Oaxaca',
           21: 'Puebla', 22: 'Querétaro', 23: 'Quintana Roo', 24: 'San Luis Potosí',
           25: 'Sinaloa', 26: 'Sonora', 27: 'Tabasco', 28: 'Tamaulipas', 29: 'Tlaxcala',
           30: 'Veracruz', 31: 'Yucatán', 32: 'Zacatecas'}

In [ ]:
def get_state(id):
    return idstate[id]

data["ID_ESTADO"] = data["ID_ESTADO"].apply(lambda x: idstate[x])

In [8]:
data.rename(columns={"ID_ESTADO": "Estado"}, inplace=True)

In [11]:
len(data["Estado"].unique())

32

In [12]:
votoExtranjero = data[data["TIPO_CANDIDATURA"]== 6]
votoLocal = data[data["TIPO_CANDIDATURA"]== 1]

In [21]:
votoExtranjero

,Estado,DISTRITO,SECCION,ID_CASILLA,TIPO_CASILLA,EXT_CONTIGUA,TIPO_ACTA,LISTA_NOMINAL,NO_VOTOS_NULOS,NO_VOTOS_CAN_NREG,...,ORDEN,PAN,APM,PBT,NA,ASDC,MUNICIPIO,PAQUETE_ENTREGADO,CASILLA_INSTALADA,FECHA_HORA
0,Aguascalientes,1,0,1,B,0,NaN,120,0.0,0.0,...,1,53.0,4.0,18.0,0.0,1.0,0,NaN,NaN,05/07/2006 23:22:10
369,Aguascalientes,2,0,1,B,0,NaN,89,0.0,0.0,...,1,50.0,3.0,14.0,0.0,6.0,0,NaN,NaN,06/07/2006 02:03:05
789,Aguascalientes,3,0,1,B,0,NaN,203,0.0,0.0,...,1,118.0,9.0,37.0,0.0,6.0,0,NaN,NaN,05/07/2006 18:09:48
1229,Baja California,1,0,1,B,0,NaN,87,0.0,0.0,...,1,45.0,6.0,21.0,1.0,1.0,0,NaN,NaN,05/07/2006 14:53:02
1621,Baja California,2,0,1,B,0,NaN,168,0.0,0.0,...,1,98.0,10.0,39.0,2.0,3.0,0,NaN,NaN,06/07/2006 05:34:11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127974,Yucatán,5,0,1,B,0,NaN,18,0.0,0.0,...,1,12.0,1.0,3.0,0.0,0.0,0,NaN,NaN,06/07/2006 09:08:19
128390,Zacatecas,1,0,1,B,0,NaN,148,0.0,0.0,...,1,45.0,8.0,49.0,0.0,1.0,0,NaN,NaN,05/07/2006 16:40:34
128940,Zacatecas,2,0,1,B,0,NaN,495,1.0,0.0,...,1,253.0,29.0,103.0,1.0,6.0,0,NaN,NaN,05/07/2006 19:50:02
129701,Zacatecas,3,0,1,B,0,NaN,126,72.0,0.0,...,1,41.0,3.0,27.0,0.0,1.0,0,NaN,NaN,05/07/2006 17:11:18
130270,Zacatecas,4,0,1,B,0,NaN,130,0.0,0.0,...,1,55.0,5.0,23.0,0.0,1.0,0,NaN,NaN,05/07/2006 19:13:29

In [22]:
votoLocal

,Estado,DISTRITO,SECCION,ID_CASILLA,TIPO_CASILLA,EXT_CONTIGUA,TIPO_ACTA,LISTA_NOMINAL,NO_VOTOS_NULOS,NO_VOTOS_CAN_NREG,...,ORDEN,PAN,APM,PBT,NA,ASDC,MUNICIPIO,PAQUETE_ENTREGADO,CASILLA_INSTALADA,FECHA_HORA
1,Aguascalientes,1,338,1,B,0,1.0,689,12.0,5.0,...,1,202.0,45.0,65.0,12.0,12.0,2,1.0,1.0,05/07/2006 08:17:05
2,Aguascalientes,1,338,1,C,0,1.0,689,7.0,11.0,...,2,175.0,38.0,56.0,3.0,8.0,2,1.0,1.0,05/07/2006 08:22:24
3,Aguascalientes,1,339,1,B,0,1.0,630,0.0,0.0,...,3,165.0,50.0,48.0,7.0,13.0,2,1.0,1.0,05/07/2006 08:24:47
4,Aguascalientes,1,339,1,C,0,1.0,631,6.0,5.0,...,4,174.0,64.0,32.0,9.0,7.0,2,1.0,1.0,05/07/2006 08:25:03
5,Aguascalientes,1,340,1,B,0,1.0,607,8.0,3.0,...,5,232.0,52.0,33.0,6.0,13.0,2,1.0,1.0,05/07/2006 08:25:27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130783,Zacatecas,4,1706,1,B,0,1.0,67,1.0,0.0,...,513,2.0,32.0,21.0,0.0,0.0,54,1.0,1.0,05/07/2006 18:34:20
130784,Zacatecas,4,1707,1,B,0,1.0,181,5.0,0.0,...,514,18.0,49.0,29.0,0.0,0.0,54,1.0,1.0,05/07/2006 18:34:44
130785,Zacatecas,4,1708,1,B,0,1.0,273,1.0,0.0,...,515,6.0,75.0,82.0,0.0,2.0,54,1.0,1.0,05/07/2006 18:35:01
130786,Zacatecas,4,1709,1,B,0,1.0,277,9.0,1.0,...,516,13.0,51.0,108.0,0.0,2.0,54,1.0,1.0,05/07/2006 18:35:17
130787,Zacatecas,4,1710,1,B,0,1.0,485,9.0,8.0,...,517,23.0,63.0,85.0,2.0,2.0,54,1.0,1.0,05/07/2006 18:35:36

In [ ]:
votoExtranjero = votoExtranjero.drop(columns=["TIPO_CANDIDATURA"])
votoLocal = votoLocal.drop(columns=["TIPO_CANDIDATURA"])

In [27]:
votoLocal.shape

(130488, 22)

In [29]:
votoExtranjero.shape

(300, 22)

In [30]:
# Obtenemos el nombre de las columnas
votoLocal.columns

Index(['Estado', 'DISTRITO', 'SECCION', 'ID_CASILLA', 'TIPO_CASILLA',
       'EXT_CONTIGUA', 'TIPO_ACTA', 'LISTA_NOMINAL', 'NO_VOTOS_NULOS',
       'NO_VOTOS_CAN_NREG', 'NO_VOTOS_VALIDOS', 'TOTAL_VOTOS', 'ORDEN', 'PAN',
       'APM', 'PBT', 'NA', 'ASDC', 'MUNICIPIO', 'PAQUETE_ENTREGADO',
       'CASILLA_INSTALADA', 'FECHA_HORA'],
      dtype='object')

In [ ]:
partidos = ["PAN", "APM", "PBT", "NA", "ASDC", "NO_VOTOS_VALIDOS", "NO_VOTOS_NULOS"]