# Clase de pandas

In [1]:
import pandas as pd
import numpy as np

In [2]:
serie = pd.Series([1, 2, 3, 4, 5])
print(serie)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
serie_letras = pd.Series(['a', 'b', 'c', 'd', 'e'])
print(serie_letras)

0    a
1    b
2    c
3    d
4    e
dtype: object

# Dataframes

In [4]:
# Crear un DataFrame a partir de un diccionario
df = pd.DataFrame({
    "Nombre": ["Pepito", "Leo", "Deivi", "Bere", "Javi"],
    "Edad": [40, 21, 26, 26, 5],
    "Salario": [1000, 2000, 3000, 4000, 5000]
})

print(df)

   Nombre  Edad  Salario
0  Pepito    40     1000
1     Leo    21     2000
2   Deivi    26     3000
3    Bere    26     4000
4    Javi     5     5000

In [5]:
# Dataframe de peliculas
## Columnas:Nombre de la peli, año, género, cantidad recaudada y calificación numérica
df_peliculas = pd.DataFrame({
    "Nombre": ["Avatar", "Titanic", "Star Wars", "Avengers", "Harry Potter"],
    "Año": [2009, 1997, 1977, 2012, 2001],
    "Género": ["Ciencia Ficción", "Romance", "Ciencia Ficción", "Acción", "Fantasía"],
    "Recaudación (USD)": [2787965087, 2187463944, 775398007, 1518812988, 974755371],
    "Calificación": [7.8, 7.8, 8.6, 8.0, 7.6]
})
print(df_peliculas)

         Nombre   Año           Género  Recaudación (USD)  Calificación
0        Avatar  2009  Ciencia Ficción         2787965087           7.8
1       Titanic  1997          Romance         2187463944           7.8
2     Star Wars  1977  Ciencia Ficción          775398007           8.6
3      Avengers  2012           Acción         1518812988           8.0
4  Harry Potter  2001         Fantasía          974755371           7.6

# Lectura de archivos CSV

In [6]:
# Leemos un archivo CSV
customers = pd.read_csv("customers-100.csv")
customers

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [7]:
customers.to_csv("customers.csv", index=False)

# Selección de datos

In [8]:
# Seleccionamos las compañias q aparecen
companias = customers["Company"]
print(companias)

0                     Rasmussen Group
1                         Vega-Gentry
2                       Murillo-Perry
3     Dominguez, Mcmillan and Donovan
4            Martin, Lang and Andrade
                   ...
95                          Carey LLC
96              Ware, Burns and Oneal
97                      Schmitt-Jones
98                 Fitzgerald-Harrell
99                 Le, Nash and Cross
Name: Company, Length: 100, dtype: object

In [9]:
# Elegir únicamente aquellas cuyo index tienen valor mayor a 50
indices = customers[customers["Index"] > 50]
gente_cuyo_nombre_empieza_con_a = customers[customers["First Name"].str.startswith("a")]
suscritos_en_2020 = customers[customers["Subscription Date"].str.contains("2020")]

# iloc: Acceso por posición
primer_cliente = customers.iloc[0]
print(primer_cliente)

Index                                         1
Customer Id                     DD37Cf93aecA6Dc
First Name                               Sheryl
Last Name                                Baxter
Company                         Rasmussen Group
City                               East Leonard
Country                                   Chile
Phone 1                            229.077.5154
Phone 2                        397.884.0519x718
Email                  zunigavanessa@smith.info
Subscription Date                    2020-08-24
Website              http://www.stephenson.com/
Name: 0, dtype: object

# Eliminar Columnas

In [13]:
customers.drop(99, axis=0)
customers

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [14]:
customers_sin_telefono = customers.drop("Phone 2", axis=1)
customers_sin_telefono

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

# Agregar datos

In [26]:
# Agregar columnas
prebes = pd.DataFrame({
    "Nombre": ["Pepito", "Leo", "Deivi", "Bere", "Javi"],
    "Edad": [40, 21, 26, 26, 5],
    "Nota": [10, 0, 0, 10, 0],
})

#Agregarme a mí mismo
prebes.loc[5] = ["Jair", 26, 10]

# Agregar Columna de Sexo
prebes["Sexo"] = ["M", "M", "M", None, "M", "M"]

prebes

   Nombre  Edad  Nota  Sexo
0  Pepito    40    10     M
1     Leo    21     0     M
2   Deivi    26     0     M
3    Bere    26    10  None
4    Javi     5     0     M
5    Jair    26    10     M

# Operaciones con datos

In [ ]:
# Promedio
prebes["Nota"].mean()
float(prebes["Nota"].mean()) # Promedio de notas en float

5.0

# F-Strings
Son una forma más fácil de formatear strings en Python

In [35]:
media_nota = float(prebes["Nota"].mean())
print(f"Los prebes obtuvieron {media_nota} en promedio de sus notas")

prebes["Edad en 50 años"] = prebes["Edad"] + 50
print(prebes)

Los prebes obtuvieron 5.0 en promedio de sus notas
   Nombre  Edad  Nota  Sexo  Edad en 50 años
0  Pepito    40    10     M               90
1     Leo    21     0     M               71
2   Deivi    26     0     M               76
3    Bere    26    10  None               76
4    Javi     5     0     M               55
5    Jair    26    10     M               76

# Ejercicio

In [ ]:
data = { 
        "Producto": ["Manzana", "Plátano", "Mango", "Manzana", "Plátano"], 
        "Precio": [12.5, 8.0, 15.0, 10.0, 7.5], 
        "Stock": [30, 45, 20, 25, 40] 
}
df = pd.DataFrame(data)

In [42]:
df.groupby("Producto")["Precio"].mean() # Agrupamos por producto y calculamos el precio promedio

Producto
Mango      15.00
Manzana    11.25
Platano     8.00
Plátano     7.50
Name: Precio, dtype: float64